# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 7, 25, 5, 51, 13, 13439, tzinfo=utc), max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
