# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitemrating_menuitemreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem'),
        ),
    ]
