# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20160726_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemrating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitemrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
