# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 25, 7, 39, 24, 528423, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 25, 7, 39, 33, 78260, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
