# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160725_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
